chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
   
]

main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('newapp.urls'),name="new_app"),
    path('chat/', include('chat.urls')),
    
]

newapp/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from newapp import views
from django.contrib.auth import views as auth_views


app_name = 'newapp'

urlpatterns = [
    path('register/',views.RegisterView,name='register'),
    path('',views.HomeView,name='home'),
    path('login/',views.LoginView,name="login"),
    path('accounts/logout/',auth_views.LogoutView.as_view(),{'next_page':'/'},name='auth_logout'),
    path('snippet/',views.snippet)
    
    
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Chat(models.Model):
    name = models.CharField(primary_key=True,max_length=200)

    def __str__(self):
        return self.name


class Message(models.Model):
    chat_room = models.ForeignKey(Chat,on_delete=models.CASCADE,blank=True,null=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.CharField(max_length=200,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username

    def last_10_messages(self):
        return Message.objects.order_by('-timestamp').all()[:10]


    

    


newapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django import forms





    
    

newapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

class UserForm(forms.ModelForm):

    password = forms.CharField(max_length=200,widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=200,widget=forms.PasswordInput())

    class Meta:

        model = User
        fields = ['first_name','last_name','username','email','password','confirm_password']
       
    def clean(self):   

        cleaned_data = super(UserForm, self).clean()
        get_password = cleaned_data.get('password')
        get_confirm_password = cleaned_data.get('confirm_password')

        if get_password != get_confirm_password:
            raise forms.ValidationError("password and confirmation password dont match")

class AuthForm(forms.Form):

    username = forms.CharField(max_length=200)
    password = forms.CharField(max_length=200,widget=forms.PasswordInput())

    class Meta:

        fields = ['username','password']

    def clean(self,*args,**kwargs):

        username=self.cleaned_data.get("username")
        password=self.cleaned_data.get("password")
            
        user=authenticate(username=username,password=password)
        if not user:
            raise forms.ValidationError("Incorrect username and password")



chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from .models import Message, Chat


# Create your views here.
@login_required(login_url='/login/')
def index(request):
    return render(request, 'chat/index.html', {})

@login_required(login_url='/login/')
def room(request, room_name):
    author = []
    content = []
        
    try:
        chat_obj = Chat.objects.get(name=room_name)
    except: 
        chat_obj = Chat.objects.create(name=room_name)
        chat_obj.save()

    message_obj = Message.objects.filter(chat_room=chat_obj)
 
    for values in message_obj:
        content.append(values.content)
        author.append(values.author)

    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name)),
        'content_and_author': zip(content,author),
        'username': request.user
    })


newapp/views.py
from django.shortcuts import render
from .forms import UserForm,AuthForm
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from django import forms
from django.contrib import messages




# Create your views here.
def RegisterView(request):

    registered = False
    if request.method == 'POST':
        user = UserForm(request.POST)
        if user.is_valid():
            username = user.cleaned_data['username']
            password = user.cleaned_data['password']
            User.objects.create_user(username=username,password=password)
            registered = True
            return render(request,'register.html',{'form':user,'registered':registered})
    else:
        user = UserForm()

    return render(request,'register.html',{'form':user,'registered':registered})


def HomeView(request):
    return render(request,'base.html')

current_user = ''
def LoginView(request):

    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                auth = authenticate(username=username,password=password) 
                if auth:             
                    login(request,auth)                               
                    return render(request,'base.html')          
        else:
            
            form = AuthForm()

        current_user = request.user.username 
    
    else:
        return render(request,'base.html')


    #current_user = request.user.username
    print(current_user)
    return render(request,'login.html',{'form':form})


def snippet(request):
    return render(request,'snippet.html')

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html>  
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>  
        <div class="jumbotron">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-6">
                        <form>
                            <div class="form-group">
                                <h4>
                                    What chat room would you like to enter?
                                </h4>
                            </div>
                            <div class="form-group">
                                <input id="room-name-input" class="form-control" type="text" size="40" placeholder="eg: abc"/>
                            </div>          
                            <div class="form-group">
                                <input id="room-name-submit" class="btn btn-primary" type="button" value="Enter"/>
                            </div>                          
                        <form>
                    </div>
                </div>
            </div>
        </div>
        

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>
{% endblock %}

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>


<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
<style> 

        .reply {
            margin-right: 90px;
            margin-left: auto;
            background-color: #ffae00;
          }
          
          .send {
            margin-right: auto;
            margin-left: 70px;   
            background-color: #00bbff;
          }
          
          .common {
            font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            max-width: 300px;
            height: 60px;
            border: 2px;
            border-radius: 10px;
            padding: 6px;
            box-shadow: 22px 24px 80px -2px rgba(0,0,0,0.29);
            margin-top: 10px;
            margin-bottom: 10px;           
          }

          .common::after {
            content: "";
            clear: both;
            display: table;
          }  

          #chat-message-input {
            margin-bottom:20px;
            margin-top: 30px;      
            height:60px;
            width:1300px;
            display:inline-block;
            margin-right:3px;
            margin-left:10px;                          
          }

          #chat-message-submit {
            height:40px; 
            width:80px;
            right:10px;
            margin-bottom:5px;            
          }

          
          
</style>
</head>
<body>

 
    
    <div class="form-group">
            {% for content, author in content_and_author %}   
                {% if author == username  %}           
                <div class='form-control common send'>
                    <span style="font-size:20px">{{ author }}</span>
                    <br>
                    {{ content }}
                </div>
                {% else %}
                <div class='form-control common reply'>
                    <span style="font-size:20px">{{ author }}</span>
                    <br>
                    {{ content }}
                </div>
                {% endif %}
            {% endfor %}
    </div>

    <div class="form-group">
        <input id="chat-message-input"   type="text" class="form-control" placeholder="Type Message" size="50"/>
        <input id="chat-message-submit" type="button" class="btn btn-primary" value="Send"/>
    </div>
   
        
    
</body>
<script>
    
        var roomName = {{ room_name_json }};

        
        var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/chat/' + roomName + '/');

    
        chatSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            var message = data['message'];
            location.reload(true);
        };
    
        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
    
        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };
    
        document.querySelector('#chat-message-submit').onclick = function(e) {
            var messageInputDom = document.querySelector('#chat-message-input');
            var message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'room_name': roomName       
            }));
    
            messageInputDom.value = '';
        };
   
</script>
</html>

{% endblock %}

newapp/templates/base.html
{% load static %}
<html>
    <head><title>New App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

  </head>

    <body>
       
     
        <!-- <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light navbar-custom"> -->
            <nav class="navbar navbar-default navbar-expand-sm navbar-light bg-light ">
                    <a class="navbar-brand" href="{% url 'newapp:home' %}">Home</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                   
                      <div class="collapse navbar-collapse" id="navbarNav">
                      <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">  
                          <a class="nav-link" href="#">About<span class="sr-only">(current)</span></a>
                        </li>
                        {% if not  request.user.is_authenticated %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'newapp:register' %}">Register</a>
                        </li>
                        
                        
                        <li class="nav-item">   
                          <a class="nav-link" href="{% url 'newapp:login' %}" tabindex="-1" aria-disabled="true">Login</a>
                        </li>
                        {% else %}

                        <li class="nav-item">   
                          <a class="nav-link" href="{% url 'chat:index' %}" tabindex="-1" aria-disabled="true">Chat</a>
                        </li>

                        <li class="nav-item">   
                          <a class="nav-link" href="{% url 'newapp:auth_logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
                        </li>

                        <li class="nav-item">   
                          <a class="nav-link" href="{% url 'newapp:home' %}" tabindex="-1" aria-disabled="true">Welcome: {{ user.username }}</a>
                        </li>


                        {% endif %} 
                      </ul>
                    </div>                 
                    </nav>
      
        
                {% block content %}
                {% endblock %}
             
                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
               
    </body>
</html>


newapp/templates/login.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="jumbotron">
    <div class="container">
            <div class="row justify-content-center">
                <div class="col-6">
            <h2>Login</h2>
            <form method="POST">
            {% csrf_token %}
            {{ form|crispy  }}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
</div>

</div>

    </div>
    </div>


{% endblock %}

newapp/templates/register.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="jumbotron">
{% if registered %}



<h1>Thank you for registering</h1>

{% else %}
<div class="container">
        <div class="row justify-content-center">
            <div class="col-6">
        <h2>Register</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy  }}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>

        </div>
        </div>
        </div>

{% endif %}


            </div>

{% endblock %}

newapp/templates/snippet.html
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<!DOCTYPE html><html class=''>
<head><script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script><meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" /><link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" /><link rel="canonical" href="https://codepen.io/michellelpepe/pen/GoQyoJ?depth=everything&order=popularity&page=84&q=pack&show_forks=false" />
<link href='https://fonts.googleapis.com/css?family=Nunito:400,300,700' rel='stylesheet' type='text/css'>

<style class="cp-pen-styles">* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Nunito', sans-serif;
}

html, body {
  background: -webkit-linear-gradient(330deg, #000, #f0a6ca);
  background: linear-gradient(120deg, #000, #f0a6ca);
  overflow: hidden;
}

.container {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  justify-content: center;
  -webkit-box-align: center;
  -ms-flex-align: center;
  align-items: center;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -ms-flex-direction: column;
  flex-direction: column;
  height: 106vh;
  width: 100vw;
}

.container h1 {
  margin: 0.5em auto;
  color: #FFF;
  text-align: center;
}



.chatbox {
  background: rgba(255, 255, 255, 0.07);
  width: 100%;
  height: 100%;
  border-radius: 0;
  position: fixed;
  box-shadow: 1px 1px 12px rgba(0, 0, 0, 0.6);
}

.chatbox__messages:nth-of-type(odd) .chatbox__messages__user-message--ind-message {
  float: right;
}

.chatbox__messages:nth-of-type(odd) .chatbox__messages__user-message--ind-message:after {
  content: '';
  position: absolute;
  margin: -1.5em -17.06em;
  width: 0;
  height: 0;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  border-right: 10px solid rgba(255, 255, 255, 0.2);
}

.chatbox__messages:nth-of-type(even) .chatbox__messages__user-message--ind-message {
  float: left;
}

.chatbox__messages:nth-of-type(even) .chatbox__messages__user-message--ind-message:after {
  content: '';
  position: absolute;
  margin: -1.5em 1.87em;
  width: 0;
  height: 0;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  border-left: 10px solid rgba(255, 255, 255, 0.2);
}

.chatbox__messages__user-message {
   width: 400px;
}

.chatbox__messages__user-message--ind-message {
  background: rgba(255, 255, 255, 0.2);
  padding: 1em 0;
  height: auto;
  width: 65%;
  border-radius: 5px;
  margin: 2em 1em;
  overflow: auto;
}

.chatbox__messages__user-message--ind-message > p.name {
  color: #FFF;
  font-size: 1em;
}

.chatbox__messages__user-message--ind-message > p.message {
  color: #FFF;
  font-size: 0.7em;
  margin: 0 2.8em;
}

.chatbox__user-list {
  background: rgba(255, 255, 255, 0.1);
  width: 25%;
  height: 100%;
  float: right;
  border-top-right-radius: 0.2em;
  border-bottom-right-radius: 0.2em;
}

.chatbox__user-list h1 {
  background: rgba(255, 255, 255, 0.05);
  color: rgba(255, 255, 255, 0.9);
  font-size: 0.9em;
  padding: 1em;
  margin: 0;
  font-weight: 300;
  text-align: center;
}

.chatbox__user, .chatbox__user--active, .chatbox__user--busy, .chatbox__user--away {
  width: 0.5em;
  height: 0.5em;
  border-radius: 100%;
  margin: 1em 0.7em;
}

.chatbox__user--active {
  background: rgba(23, 190, 187, 0.8);
}

.chatbox__user--busy {
  background: rgba(252, 100, 113, 0.8);
}

.chatbox__user--away {
  background: rgba(255, 253, 130, 0.8);
}

.chatbox p {
  float: left;
  text-align: left;
  margin: -0.25em 2em;
  font-size: 0.7em;
  font-weight: 300;
  color: #FFF;
  width: 200px;
}

.chatbox form {
  background: #222;
}

.chatbox form input {
  background: rgba(255, 255, 255, 0.03);
  position: absolute;
  bottom: 0;
  left: 0;
  border: none;
  width: 75%;
  padding: 1.2em;
  outline: none;
  color: rgba(255, 255, 255, 0.9);
  font-weight: 300;
}

::-webkit-input-placeholder {
  color: rgba(255, 255, 255, 0.9);
}

:-moz-placeholder {
  color: rgba(255, 255, 255, 0.9);
}

::-moz-placeholder {
  color: rgba(255, 255, 255, 0.9);
}

:-ms-input-placeholder {
  color: rgba(255, 255, 255, 0.9);
}



.chatbox__anil {
  position: absolute;
  margin: -1.5em -17.06em;
  width: 100px;
  height: 100px;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  border-right: 10px solid rgba(255, 255, 255, 0.2);
}

.chatbox__anil_one {
  background: rgba(255, 255, 255, 0.2);
  padding: 1em 0;
  height: auto;
  width: 65%;
  border-radius: 5px;
  margin: 2em 1em;
  overflow: auto;
}

.chatbox__anil_two {
  float: left;
}



</style></head><body>
<div ng-cloak ng-app="chatApp">
  
  <div class='chatbox' ng-controller="MessageCtrl as chatMessage">
    <div class='chatbox__user-list'>
      <h1>Friends Online</h1>
      <div class='chatbox__user--active'>
        <p>Maelyn Pepe</p>
      </div>
      <div class='chatbox__user--busy'>
        <p>Michelle Pepe</p>
      </div>
      <div class='chatbox__user--active'>
        <p>Amy Angular</p>
      </div>
      <div class='chatbox__user--active'>
        <p>Jack Uniden</p>
      </div>
      <div class='chatbox__user--away'>
        <p>Ben Marcus</p>
      </div>
    </div>
    <div class="chatbox__messages" ng-repeat="message in messages"> 
       <div class="chatbox__messages__user-message">
        <div class="chatbox__messages__user-message--ind-message">
          <p class="name">{{message.Name}}</p>
          <br/>
          <p class="message">{{message.Message}}</p>
        </div>
      </div>
    </div>
    
    
    <form>
      <input type="text" placeholder="Type Message">
    </form>
  </div>
<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script><script src='//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js'></script><script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script >(function() {
  var app = angular.module('chatApp', []);

  app.controller('MessageCtrl', function($scope) {
    $scope.messages = [{
      Name: 'Ben Marcus',
      Message: "Hi  : )"
    }, {
      Name: 'Michelle Pepe',
      Message: "What's up?"
    }, {
      Name: 'Ben Marcus',
      Message: "Nothing much, You?"
    }];
  });

})();
//# sourceURL=pen.js
</script>
</body></html>